# -*- coding: utf-8 -*-
"""clean2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6bsdRewD4hkkYcsyWJSDJsYZhl1PhXH
"""

import pandas as pd
import os

# Ensure data_clean directory exists
output_dir = "data_clean"
os.makedirs(output_dir, exist_ok=True)

# Load dataset
file_path = "/content/StudentsPerformance.csv"  # Update path if needed
df = pd.read_csv(file_path)

# Standardize column names (lowercase and replace spaces with underscores)
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")


# Fill missing numerical values with the mean
num_cols = df.select_dtypes(include=["number"]).columns
df[num_cols] = df[num_cols].apply(lambda x: x.fillna(x.mean()))

# Fill missing categorical values with the mode
cat_cols = df.select_dtypes(include=["object"]).columns
df[cat_cols] = df[cat_cols].apply(lambda x: x.fillna(x.mode()[0]))



# Save cleaned dataset
cleaned_file_path = os.path.join(output_dir, "cleaned_student_performance.csv")
df.to_csv(cleaned_file_path, index=False)

print("\n Data cleaning complete. Missing values replaced. Cleaned data saved at:", cleaned_file_path)