# -*- coding: utf-8 -*-
"""cleandata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134Ts8QTmNkDZZ2nLFJyCdZWyMfHZKvk8
"""

import pandas as pd
import os

# Define file paths (update as needed)
file_path = "/content/raw data.csv"
cleaned_file_path = "cleaned_frailty_data.csv"

# Load dataset
df = pd.read_csv(file_path)

# Standardize column names
df.columns = df.columns.str.strip().str.lower()

# Check if 'frailty' column exists
if "frailty" not in df.columns:
    raise KeyError("Column 'Frailty' not found. Check CSV headers.")

# Drop rows with missing values in 'frailty' before conversion
df = df.dropna(subset=["frailty"])

# Convert 'frailty' (Y/N) to binary (1 = Yes, 0 = No)
df["frailty"] = df["frailty"].map({"Y": 1, "N": 0})

# Save cleaned dataset
df.to_csv(cleaned_file_path, index=False)

print(f"Data cleaning completed. Cleaned data saved at: {cleaned_file_path}")